workflows: ci-test-dev: add step to fail if bad user input combo
Addition of a step to fail the workflow if the user has specified a
test or test group, but not specified a firmware type to use.

Signed-off-by: James Hershaw <james.hershaw@corigine.com>
Reviewed-by: Jaco Coetzee <jaco.coetzee@corigine.com>
Reviewed-by: Annemie Potgieter <annemie.potgieter@corigine.com>
Signed-off-by: Louis Peens <louis.peens@corigine.com>

diff --git a/.github/workflows/ci-test-dev.yaml b/.github/workflows/ci-test-dev.yaml
--- a/.github/workflows/ci-test-dev.yaml
+++ b/.github/workflows/ci-test-dev.yaml
@@ -122,6 +122,12 @@ jobs:
                     }
           print(json.dumps(inputs, indent=1))
 
+      - name: Fail if test specified but not fw_type
+        if: inputs.test != 'all' && inputs.fw_type == 'AUTO:all'
+        run: |
+          echo "::error::Test specified but not firmware type"
+          exit 1
+
       - name: Checkout provisioning repo
         uses: actions/checkout@v3
         with:
